### ISSUE TITLE
Issue in acc module in 4.3?

### ISSUE THREAD

**Issue by mtryfoss** [kamailio/kamailio#350] opened 2015-10-01 12:40 UTC
I've found some strange cdr records produced by kamailio. Haven't experienced this before in earlier versions.

One example (last field is kamailios call duration):
1442923048|1442923184|136298900000.000000
The duration of this call is in reality ~136 seconds. This matches the first three digits of the duration-field. Is this just a coincidence?

Another example:
1443011985|1443012286|301148.400000
This call has a duration of 301 seconds. Same as the first three digits.

I haven't found anything special with these calls, and it doesn't seem possible to reproduce. Just happens sometimes.

Settings for acc module:
modparam("acc", "db_url", "flatstore:/accounting")
modparam("acc", "log_level", 3)
modparam("acc", "cdr_enable", 1)
modparam("acc", "cdr_start_on_confirmed", 1)
modparam("acc", "cdr_extra", "anum=$dlg_var(caller);bnum=$dlg_var(callee);dlg_start_time=$dlg_var(inv_start);cancel_time=$dlg_var(cancel);account=$dlg_var(account);calltype=$dlg_var(calltype);callid=$dlg_var(callid);callid_system=$dlg_var(callid_system);trunk_id=$dlg_var(trunk_id)")
modparam("dialog", "dlg_flag", 4)
modparam("acc", "cdrs_table", "cdr")
modparam("acc", "cdr_on_failed", 0)

**Comment by miconda** [comment] 2015-10-01 13:11
Checking quickly the logs, I see that the column types where changed from string/varchar to datetime and double. What is your structure for cdr table?

**Comment by mtryfoss** [comment] 2015-10-01 13:35
I'm using flatstore.

**Comment by miconda** [comment] 2015-10-03 11:38
It might have been related to a race when storing dlg variable in database, which should be fixed in 4.3.3. Can you update and try to see if that was the issue?

I stress tested after the fix with sipp, in chunks of 50k calls at 400cps with max 4k of active calls and the duration seemed to be ok.

**Comment by mtryfoss** [comment] 2015-10-05 10:08
I will test with the newest version and let you know. Thank you.

**Comment by miconda** [comment] 2015-10-19 14:33
Going to close this one, re-open if the issue is there with the latest version.

**Closed by miconda** 2015-10-19 14:33 UTC
