### ISSUE TITLE
Authenticating Custom Username

### ISSUE THREAD

**Issue by prabhat2k15** [kamailio/kamailio#1818] opened 2019-01-22 07:19 UTC
There is no function for authenticating custom username like
pv_www_authenticate(realm, passwd, flags [, method])

Purpose: The purpose behind this is i want to modify username and then authenticate according to credentials saved in DB.

**Comment by henningw** [comment] 2019-01-25 09:01
Duplicate of #1817

**Closed by henningw** 2019-01-25 09:01 UTC
