### ISSUE TITLE
AOR value at event_route[usrloc:contact-expired] has no domain part even with usrloc.use_domain == 1

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#3365] opened 2023-02-09 15:32 UTC
### Description

When event_route[usrloc:contact-expired] is triggered, the pseudo-var $ulc(exp=>aor) contains only the userpart of the aor of the expired registration

### Troubleshooting

```
modparam("usrloc", "use_domain", 1)
[...]
event_route[usrloc:contact-expired]
{
	xlog("L_NOTICE", "Contact ruid $ulc(exp=>ruid) to $ulc(exp=>addr) for user $ulc(exp=>aor) expired\n");
}
```

#### Log Messages

REGISTER... AOR is ``43991002@ce-trunk.lab``
```
│Feb  9 16:19:47.152646 spce proxy[22541]: DEBUG: ROUTE_REG_HANDLE usrloc [udomain.c:697]: db_load_urecord(): aor 43991002@ce-trunk.lab not found in table location
│Feb  9 16:19:47.152816 spce proxy[22541]: DEBUG: ROUTE_REG_HANDLE registrar [path.c:108]: build_path_vector(): received is <sip:192.168.2.177:5160>
│Feb  9 16:19:47.152843 spce proxy[22541]: DEBUG: ROUTE_REG_HANDLE registrar [path.c:116]: build_path_vector(): path is <<sip:lb@127.0.0.1;lr;received=sip:192.168.2.177:5160;socket=sip:192.168.2.70:5060>>
│Feb  9 16:19:47.152866 spce proxy[22541]: DEBUG: ROUTE_REG_HANDLE registrar [save.c:421]: pack_ci(): generated ruid is: uloc-63e50ec8-580d-1
│Feb  9 16:19:47.154051 spce proxy[22541]: DEBUG: ROUTE_REG_HANDLE registrar [reply.c:334]: build_contact(): created Contact HF: Contact: <sip:43991002@192.168.2.177:5160>;expires=600;received="sip:192.168.2.177:5160"#015#012
│Feb  9 16:19:47.154354 spce proxy[22541]: NOTICE: ROUTE_REG_HANDLE <script>: Contacts successfully saved, expires in 600s - R=«sip:ce-trunk.lab» ID=«pgflewbuqnvhmid@debbox.lab» UA='Twinkle/1.10.2' 
```

let it expire.. AOR in event_route[usrloc:contact-expired] is ``43991002``
```
│Feb  9 16:30:32.980631 spce proxy[22543]: DEBUG: usrloc [udomain.c:1050]: udomain_contact_expired_cb(): calling contact expired records - cycle [1]
│Feb  9 16:30:32.980655 spce proxy[22543]: DEBUG: usrloc [ul_callback.h:83]: run_ul_callbacks(): contact=0x7f434b8a1220, callback type 8/8, id 0 entered
│Feb  9 16:30:32.980776 spce proxy[22543]: DEBUG: registrar [regpv.c:734]: reg_ul_expired_contact(): saved contact for <43991002> in [exp]
│Feb  9 16:30:32.980799 spce proxy[22543]: NOTICE: usrloc:contact-expired <script>: Contact ruid uloc-63e50ec8-580d-1 to sip:43991002@192.168.2.177:5160 for user 43991002 expired
```
### Possible Solutions

PR will follow with possible solution

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

This is kamailio Sipwise flavor

```
version: kamailio 5.6.2 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, NO_SIG_DEBUG, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 10.2.1
```

**Comment by miconda** [comment] 2023-02-09 16:05
Is it for db-only case, or when the records are in memory?

**Comment by linuxmaniac** [comment] 2023-02-09 16:13
I tested just for the db-only case

**Comment by miconda** [comment] 2023-02-09 17:05
For in memory records, their is an aor field in the structure and that was used. I think the db-only support for executing event route on expire was added later, maybe the aor is not constructed properly for loaded db records.

**Comment by linuxmaniac** [comment] 2023-02-09 18:47
Fix the fix applied, all seems fine.
```
│Feb  9 16:47:58.089067 spce proxy[30268]: DEBUG: usrloc [udomain.c:1053]: udomain_contact_expired_cb(): calling contact expired records - cycle [1]
│Feb  9 16:47:58.089100 spce proxy[30268]: DEBUG: usrloc [ul_callback.h:83]: run_ul_callbacks(): contact=0x7f8859ed4f50, callback type 8/8, id 0 entered
│Feb  9 16:47:58.089197 spce proxy[30268]: DEBUG: registrar [regpv.c:734]: reg_ul_expired_contact(): saved contact for <43991002@ce-trunk.lab> in [exp]
│Feb  9 16:47:58.089220 spce proxy[30268]: NOTICE: usrloc:contact-expired <script>: Contact ruid uloc-63e5131a-7639-1 to sip:43991002@192.168.2.177:5160 for user 43991002@ce-trunk.lab expired
```

**Comment by miconda** [comment] 2023-02-13 11:11
I wanted to narrow where the issue is, because the description didn't mentioned db-only mode, which I think support for it was added later for execution of event route. If it would have been also for in-memory records modes, the impact could have been larger on other features.

Given that it was discovered for db-only, the PR can be merged.

**Closed** 2023-02-13 11:24 UTC
