### ISSUE TITLE
Permissions: kamcmd permissions.addressDump -- error: 500 - Internal error creating rpc ih

### ISSUE THREAD

**Issue by eschmidbauer** [kamailio/kamailio#234] opened 2015-07-06 15:43 UTC
Hello,
When we have 64 or more records in same 'grp'
kamcmd permissions.addressDump fails with "error: 500 - Internal error creating rpc ih"
I'm guessing this is a problem with the size of the *ih variable. Can it be increased to accommodate larger datasets?
Thanks,
Emmanuel

**Comment by miconda** [comment] 2015-07-14 13:41
You may need to adjust the buffers of ctl module via its parameters. I am going to close this one, re-open if the issue is still there after tuning those buffers.

Also, as a side node, check the syslog to see if there are other error messages printed there.

**Closed by miconda** 2015-07-14 13:41 UTC
