### ISSUE TITLE
Errors work BLF modules pua and presence

### ISSUE THREAD

**Issue by klistrod** [kamailio/kamailio#104] opened 2015-03-04 12:13 UTC
Errors work BLF modules pua and presence:
```
loadmodule "presence.so"
loadmodule "presence_xml.so"
loadmodule "presence_dialoginfo.so"
loadmodule "pua.so"
loadmodule "pua_dialoginfo.so"

modparam("presence", "db_url", DBURL)
modparam("presence_xml", "db_url", DBURL)
modparam("presence_xml", "force_active", 1)
modparam("presence_dialoginfo", "force_single_dialog", 1)


 5(18085) ERROR: presence [publish.c:139]: msg_presentity_clean(): event not found
 5(18085) ERROR: db_mysql [km_dbase.c:123]: db_mysql_submit_query(): driver error on query: Duplicate entry 'a.1425449702.18081.57.5---' for key 'pua_idx'
 5(18085) ERROR: <core> [db_query.c:335]: db_do_update(): error while submitting query
 5(18085) ERROR: pua [pua.c:1079]: db_update(): while updating in database
```

**Comment by miconda** [comment] 2015-03-13 09:00
Are you inserting somehow recordds directly to the database? The error says that event value was not in the database.

The second is about a duplicate key that shows only etag, can you look at the pua table in database and see if there are values for call_id, from_tag and tuple_id?

What database engine you use? Kamailio version?

**Comment by miconda** [comment] 2015-07-15 07:35
Closing as no follow up was made for about 4 months. Re-open and add requested details if the issue is still there for you.

**Closed by miconda** 2015-07-15 07:35 UTC
