### ISSUE TITLE
cfgt: wrong flow if route has no last action return

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#569] opened 2016-04-15 11:12 UTC
The actual implementation is based on the cfg actions, so when there is no 'return' action defined the route flow detected is wrong.

**Comment by miconda** [comment] 2018-12-24 10:00
Is still an issue, or it was fixed with latest devel cycles?

**Comment by henningw** [comment] 2019-02-12 09:09
@linuxmaniac - any update on this?

**Comment by henningw** [comment] 2019-04-25 19:47
No update since a few months. As the issue is from 2016 I am going to close this one. Please re-open with more details if the problem is still valid.

**Closed by henningw** 2019-04-25 19:47 UTC
Labels: 4.4, bug
