### ISSUE TITLE
segmentation fault on kamailio 5.4.4

### ISSUE THREAD

**Issue by descartin** [kamailio/kamailio#3039] opened 2022-02-24 13:04 UTC
hello all

we have seen a segmentation fault on a kamailio 5.4.4

```
#0  0x00007feb664346ad in print_lists (dlg=0x7feaa5f65290) at dlg_var.c:277
277				varlist = varlist->next;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 elfutils-libelf-0.166-2.el7.x86_64 elfutils-libs-0.166-2.el7.x86_64 glibc-2.17-157.el7_3.5.x86_64 jansson-2.10-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-9.el7.x86_64 libcurl-7.29.0-35.el7.centos.x86_64 libev-4.15-7.el7.x86_64 libevent-2.0.21-4.el7.x86_64 libgcc-4.8.5-16.el7.x86_64 libidn-1.28-4.el7.x86_64 libselinux-2.5-6.el7.x86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libuuid-2.23.2-33.el7_3.2.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 nspr-4.13.1-1.0.el7_3.x86_64 nss-3.28.4-1.2.el7_3.x86_64 nss-softokn-freebl-3.16.2.3-14.4.el7.x86_64 nss-util-3.28.4-1.0.el7_3.x86_64 openldap-2.4.40-13.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 systemd-libs-219-30.el7_3.9.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007feb664346ad in print_lists (dlg=0x7feaa5f65290) at dlg_var.c:277
#1  0x00007feb664367ff in pv_set_dlg_variable (msg=0x7feb6a881bd8, param=0x7feb6adc85a0, op=254, val=0x7ffea166a7a0) at dlg_var.c:443
#2  0x00000000004bbaf2 in lval_pvar_assign (h=0x7ffea166bbd0, msg=0x7feb6a881bd8, lv=0x7feb6adc8668, rv=0x7feb6adc87e8) at core/lvalue.c:352
#3  0x00000000004bc5f0 in lval_assign (h=0x7ffea166bbd0, msg=0x7feb6a881bd8, lv=0x7feb6adc8668, rve=0x7feb6adc87e0) at core/lvalue.c:400
#4  0x0000000000487ddf in do_action (h=0x7ffea166bbd0, a=0x7feb6adc8f80, msg=0x7feb6a881bd8) at core/action.c:1455
#5  0x0000000000489b1b in run_actions (h=0x7ffea166bbd0, a=0x7feb6adc8338, msg=0x7feb6a881bd8) at core/action.c:1581
#6  0x000000000047c6d7 in do_action (h=0x7ffea166bbd0, a=0x7feb6adce4c0, msg=0x7feb6a881bd8) at core/action.c:1067
#7  0x0000000000489b1b in run_actions (h=0x7ffea166bbd0, a=0x7feb6adc3190, msg=0x7feb6a881bd8) at core/action.c:1581
#8  0x000000000048a25f in run_top_route (a=0x7feb6adc3190, msg=0x7feb6a881bd8, c=0x7ffea166bbd0) at core/action.c:1666
#9  0x00007feb69eab0a2 in reply_received (p_msg=0x7feb6a881bd8) at t_reply.c:2543
#10 0x000000000059dc77 in do_forward_reply (msg=0x7feb6a881bd8, mode=0) at core/forward.c:764
#11 0x000000000059f949 in forward_reply (msg=0x7feb6a881bd8) at core/forward.c:865
#12 0x00000000005f095a in receive_msg (
    buf=0xacec80 <buf.7134> "SIP/2.0 100 Trying\r\nVia: SIP/2.0/UDP 79.170.70.13;branch=z9hG4bK7837.ffc6315fbd54de1e6a00b32fa1cc0eda.1\r\nVia: SIP/2.0/UDP 79.170.66.28:5080;received=79.170.66.28;rport=5080;branch=z9hG4bK83ve3c7ty27QF"..., len=426, rcv_info=0x7ffea166c6c0) at core/receive.c:509
#13 0x00000000004e3cd7 in udp_rcv_loop () at core/udp_server.c:543
#14 0x0000000000429f56 in main_loop () at main.c:1689
#15 0x0000000000434034 in main (argc=15, argv=0x7ffea166cf58) at main.c:2876
```

[Uploading core_kamailio_mia_osp_feb18.log…]()

could you please take a look to the attached full backtrace?

thanks a lot and regards
david

**Comment by henningw** [comment] 2022-02-24 13:15
duplicate of #3040

**Closed by henningw** 2022-02-24 13:15 UTC
Labels: duplicate
