### ISSUE TITLE
no config routing engine registered

### ISSUE THREAD

**Issue by kachallah** [kamailio/kamailio#1619] opened 2018-08-10 12:46 UTC
Hi everyone, I want to set up a network core with kamailio ims using the external HSS but when I try to connect with the user bob, I get this problem: <no config routing engine registered>. Thank you for supporting me

**Comment by kamailio-sync** [comment] 2018-08-10 13:15
Am Freitag, 10. August 2018, 14:46:56 CEST schrieb kachallah:
> Hi everyone, I want to set up a network core with kamailio ims using the
> external HSS but when I try to connect with the user bob, I get this
> problem: <no config routing engine registered>. Thank you for supporting me

Hello,

do you have a cfgengine statement in your kamailio.cfg?

Its not documented in the wiki, this is an excerpt from the git

    core: cfgengine - new global parameter/statement
    
    - set the config interpreter engine, can be used like:
    
      cfgengine="name"
      cfgengine "name"
    
    If name is "native" or "default", it expects to have in native config
    interpreter for routing logic.
    
    The name can be the identifier of an embedded language interpreter, such
    as "lua" which is registered by the app_lua module:
    
      cfgengine "lua"

Best regards,

Henning
-- 
Henning Westerholt
https://skalatan.de/blog/

**Comment by kachallah** [comment] 2018-08-11 00:54
Hi thanks for your support,

In the different entities (pcscf, icscf, scscf) I have a kamailio.cfg file. On which kamailio.cfg must add cfgengine = "name"

**Comment by henningw** [comment] 2018-08-12 08:14
Hello, 

If you don't use this functionality then you should not need to add this cfgengine statement to the configuration file.

Can you please give a bit more information about your error, for example:

- relevant log files from kamailio
- kamailio version
- if you have cfgengine statement in your kamailio.cfg file
- does this error happens for every SIP message, or just a few

**Comment by miconda** [comment] 2018-08-14 08:50
If you didn't want to go for KEMI interpreters, then likely your config is not having the `request_route { ... }` block and you received a SIP request. See default `kamailio.cfg` for its structure and what should be done in `request_route`.

I enhanced the error log message to be more explicit in this situation. I am closing this one, if you still need assistance, then send an email to sr-users@lists.kamailio.org, the problem to solve is how to use kamailio, not a bug in the code.

**Closed by miconda** 2018-08-14 08:50 UTC

**Comment by kachallah** [comment] 2018-08-29 09:00
Hello everyone, finally I was able to set up Ims kamailio. Because I noticed that the icscf entity does not know how to join the scscf entity. To remedy this I have to replace my iscsf table with the openimscore iscsf table. Thank you all and have a nice day

**Comment by leechul** [comment] 2018-09-13 02:54
Hi kachallah.
I want to setup kamailio ims to... could you please help to share pcscf scscf icscf configuration example?

**Comment by kachallah** [comment] 2018-09-13 08:39
Hi Leechul,
Go to my blog and see all that need to install and config it : http://kachou92.over-blog.com/2018/09/volte-kamailio-ims.html

**Comment by leechul** [comment] 2018-09-14 03:49
apt-get install seems diffrent than 5.1.5 version.
where can i find a example for the IMS, using the kamailio 5.1.5 version....

**Comment by kachallah** [comment] 2018-09-14 10:32
I use this script : http://repository.ng-voice.com/install.sh 
and my version is 5.1.0-dev6

**Comment by kachallah** [comment] 2018-09-14 10:53
but i can download the source code from : https://www.kamailio.org/pub/kamailio/latest-5.1.x/src/kamailio-5.1.5_src.tar.gz
