### ISSUE TITLE
Private memory leaking in case of topos(redis) and topoh modules enable together

### ISSUE THREAD

**Issue by alexey-khabulyak** [kamailio/kamailio#1682] opened 2018-10-20 18:54 UTC
### Description

I tested kamailio's topoh+topos modules. udp worker's private memory is leaking when i enable both.  
after a couple of hour kamailio stops and spams error messages.

### Troubleshooting
kamcmd pkg.stats shows lots of real_used memory(only udp workers are leaking).

#### Reproduction
Enable both modules.

#### Log Messages

```
Oct 18 17:00:55  /usr/sbin/kamailio[20801]: ERROR: <core> [core/receive.c:162]: receive_msg(): no mem for sip_msg
Oct 18 17:00:55  /usr/sbin/kamailio[20802]: ERROR: <core> [core/mem/q_malloc.c:291]: qm_find_free(): qm_find_free(0x7fe6f5bee010, 1776); Free fragment not found!
Oct 18 17:00:55  /usr/sbin/kamailio[20802]: ERROR: <core> [core/mem/q_malloc.c:425]: qm_malloc(): qm_malloc(0x7fe6f5bee010, 1776) called from core: core/receive.c: receive_msg(160), module: core; Free fragment not found!
```

### Possible Solutions

disable one of modules
### Additional Information
* **/etc/default/kamailio** 
```
SHM_MEMORY=512
PKG_MEMORY=64
```
Number of children = 8

* **Parameters**:
```
loadmodule "topoh.so"
modparam("topoh", "mask_key", "N2hkVvBTxJ6Y")
modparam("topoh", "mask_callid", 0)
modparam("topoh", "sanity_checks", 1)
modparam("topoh", "uri_prefix_checks", 1)
modparam("topoh", "mask_ip", MY_IP_ADDR)
loadmodule "topos.so"
loadmodule "topos_redis.so"
modparam("topos", "storage", "redis")
modparam("topos", "branch_expire", 300)
modparam("topos", "dialog_expire", 10800)
modparam("topos", "clean_interval", 30)
modparam("topos_redis", "serverid", "topo")
```
  * **Kamailio Version** - output of `kamailio -v`

```
# kamailio -v
version: kamailio 5.1.6 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 4.9.2
```

* **Operating System**:

```
Debian 8.10
```

**Comment by miconda** [comment] 2018-10-24 06:00
The modules were designed to be used one or the other, they are using same callback hooks and internal mechanism to replace old message buffer, using one after the other, likely to leak in stage in the middle of the message buffer.

I can look and see if there is anything that can be done. As a safety option when nothing else can be done or is too complex to consider, I can add a check in each module so that if the other one is loaded to stop starting kamailio...

**Comment by alexey-khabulyak** [comment] 2018-10-24 06:54
I want to use only topos module. i was confused when i read topoS documentation. have it sanity_check parameter? config modparam("topoh", "sanity_checks", 1) contains topoH module instead of topos. this is why i enable both.

is it typo? modparam("topos", "sanity_checks", 1)

https://www.kamailio.org/docs/modules/5.1.x/modules/topos.html
thank you in advance

**Comment by miconda** [comment] 2018-10-24 07:02
That's a typo, being couple of mod params with the same purpose in the two modules, I did some copy&paste from topoh (older module) and topos. I will fix the docs, thanks for pointing it out.

**Comment by alexey-khabulyak** [comment] 2018-10-24 07:05
thanks a lot

**Comment by miconda** [comment] 2018-11-30 15:09
Closing this one, given the solution above and not expecting to use the two modules at the same time. That could be an enhancement in the future, for now it is not a bug.

**Closed by miconda** 2018-11-30 15:09 UTC
