### ISSUE TITLE
Some warnings during build

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1712] opened 2018-11-07 18:04 UTC
### Description
This in not important and may be closed at any time.

Some info about build warnings on Alpine dist

#### Reproduction

start a build process on Alpine dist

#### Debugging Data

NA

#### Log Messages

```
CC (gcc) [M regex.so]		regex_mod.o
regex_mod.c: In function 'w_pcre_match_group':
regex_mod.c:663:9: warning: 'num_pcre' may be used uninitialized in this function [-Wmaybe-uninitialized]
  return ki_pcre_match_group(_msg, &string, (int)num_pcre);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LD (gcc) [M regex.so]		regex.so
CC (gcc) [M db_berkeley.so]		bdb_fld.o
```
Next
```
CC (gcc) [M cplc.so]		cpl_parser.o
In file included from ../../core/mem/mem.h:41:0,
                 from cpl_run.c:37:
cpl_run.c: In function 'run_remove_location':
../../core/mem/../dprint.h:302:8: warning: 'url.len' may be used uninitialized in this function [-Wmaybe-uninitialized]
        fprintf(stderr, "%2d(%d) %s: %.*s%s" fmt, \
        ^~~~~~~
cpl_run.c:416:6: note: 'url.len' was declared here
  str url;
      ^~~
CC (gcc) [M cplc.so]		sub_list.o
make[3]: 'libsrdb1.so.1.0' is up to date.
```
Next
```
CC (gcc) [M db2_ldap.so]		ld_fld.o
ld_fld.c: In function 'ldap_gentime2db_datetime':
ld_fld.c:273:10: warning: implicit declaration of function 'timelocal' [-Wimplicit-function-declaration]
   *dst = timelocal(&time);
          ^~~~~~~~~
CC (gcc) [M db2_ldap.so]		ld_cmd.o
```
Next
```
CC (gcc) [M auth_identity.so]		auth_dynstr.o
CC (gcc) [M auth_identity.so]		auth_crypt.o
auth_crypt.c:29:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>:0:0: note: this is the location of the previous definition
```

Next
```
CC (gcc) [M tls.so]		tls_init.o
tls_init.c:320:13: warning: 'ser_free' defined but not used [-Wunused-function]
 static void ser_free(void *ptr, const char *fname, int fline)
             ^~~~~~~~
CC (gcc) [M tls.so]		tls_dump_vf.o
CC (gcc) [M tls.so]		tls_select.o
CC (gcc) [M tls.so]		tls_cfg.o
CC (gcc) [M tls.so]		tls_map.o
CC (gcc) [M tls.so]		tls_server.o
CC (gcc) [M tls.so]		tls_locking.o
tls_locking.c:85:13: warning: 'dyn_destroy_f' defined but not used [-Wunused-function]
 static void dyn_destroy_f(struct CRYPTO_dynlock_value *l,
             ^~~~~~~~~~~~~
tls_locking.c:67:13: warning: 'dyn_lock_f' defined but not used [-Wunused-function]
 static void dyn_lock_f(int mode, struct CRYPTO_dynlock_value* l,
             ^~~~~~~~~~
tls_locking.c:45:37: warning: 'dyn_create_f' defined but not used [-Wunused-function]
 static struct CRYPTO_dynlock_value* dyn_create_f(const char* file, int line)
                                     ^~~~~~~~~~~~
CC (gcc) [M tls.so]		tls_domain.o
tls_domain.c:872:12: warning: 'tls_ssl_ctx_set_freelist' defined but not used [-Wunused-function]
 static int tls_ssl_ctx_set_freelist(SSL_CTX* ctx, long val, void* unused)
            ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from tls_domain.c:33:0:
tls_domain.c: In function 'load_engine_private_key':
tls_map.h:46:14: warning: 'pkey' may be used uninitialized in this function [-Wmaybe-uninitialized]
   ( (m)->tmp = (value),\
              ^
tls_domain.c:1183:12: note: 'pkey' was declared here
  EVP_PKEY *pkey;
            ^~~~
CC (gcc) [M tls.so]		tls_util.o
```
Next
```
CC (gcc) [M ims_usrloc_pcscf.so]		dlist.o
In file included from usrloc_db.c:10:0:
usrloc_db.c: In function 'db_update_pcontact':
usrloc_db.h:46:25: warning: 'service_routes.len' may be used uninitialized in this function [-Wmaybe-uninitialized]
    VAL_STR((_val)).len  = (_str).len;\
                         ^
usrloc_db.c:122:13: note: 'service_routes.len' was declared here
  str impus, service_routes;
             ^~~~~~~~~~~~~~
In file included from usrloc_db.c:10:0:
usrloc_db.h:45:24: warning: 'service_routes.s' may be used uninitialized in this function [-Wmaybe-uninitialized]
    VAL_STR((_val)).s   = (_str).s;\
                        ^
usrloc_db.c:122:13: note: 'service_routes.s' was declared here
  str impus, service_routes;
             ^~~~~~~~~~~~~~
CC (gcc) [M ims_usrloc_pcscf.so]		pcontact.o
```
Next
```
CC (gcc) [M evapi.so]		evapi_mod.o
evapi_dispatch.c: In function 'evapi_run_dispatcher':
evapi_dispatch.c:699:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  ev_io_init(&io_server, evapi_accept_client, evapi_srv_sock, EV_READ);
  ^~~~~~~~~~
evapi_dispatch.c:699:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
evapi_dispatch.c:699:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
evapi_dispatch.c:699:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
evapi_dispatch.c:701:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  ev_io_init(&io_notify, evapi_recv_notify, _evapi_notify_sockets[0], EV_READ);
  ^~~~~~~~~~
evapi_dispatch.c:701:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
evapi_dispatch.c:701:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
evapi_dispatch.c:701:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
make[3]: 'libsrutils.so.1.0' is up to date.
LD (gcc) [M evapi.so]		evapi.so
```

#### SIP Traffic
NA

### Additional Information

Compiled master on Alpine 3.8 dist
If this is fixed, then i can provide more warnings.

**Comment by henningw** [comment] 2018-11-09 10:10
Thanks for the report. I looked into the TLS warnings, can't reproduce them. What gcc version did you used on the Alpine 3.8 distribution?

**Comment by sergey-safarov** [comment] 2018-11-09 10:44
GCC version
```
/ # gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/8.2.0/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-8.2.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 8.2.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,objc,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
gcc version 8.2.0 (Alpine 8.2.0) 
```
About TLS
Think this may be related to used `lebressl` instreat `openssl`. And related to https://github.com/kamailio/kamailio/issues/1670

**Comment by linuxmaniac** [comment] 2018-11-09 11:10
You can check [travis sid](https://travis-ci.org/kamailio/kamailio/jobs/452790092) build output its gcc 8.2.0

**Comment by miconda** [comment] 2018-12-17 19:42
I pushed two patches to regex and cplc modules, even they looked more like false positives.

The `timelocal()` is defined in time.h according to man page and that file is included. TLS was sorted out, ims modules need an overall review for warnings.

Also, the debian sid build didn't show any of these warnings.

I am closing it, as they show up in punctual builds, then we can approach again.

**Closed by miconda** 2018-12-17 19:42 UTC
