### ISSUE TITLE
Return values for $Au don't match the documentation

### ISSUE THREAD

**Issue by joelsdc** [kamailio/kamailio#2056] opened 2019-09-05 16:10 UTC
### Description

Testing on latest master deb nightly build (`5.3.0~dev7+0~20190904005559.1479+buster`) I've noticed that `$Au` is not being set correctly, at least according to my tests.

From the documentation (https://www.kamailio.org/wiki/cookbooks/devel/pseudovariables#au_-_acc_username): 

_$Au - Acc username: username for accounting purposes. It's a selective pseudo variable (inherited from acc module). It returns auth username ($au) if exists or From username ($fU) otherwise._

I have the following log statement in several places in a test box:

xlog("L_NOTICE", "[DEBUG] Au=$Au au=$au aU=$aU ar=$ar fU=$fU fu=$fu - \n");

And when I run through them I get the following:

Initial log (at the beginning of request_route):

```
Sep  5 01:54:39 csbc01 csbc[20380]: NOTICE: {1 1 REGISTER f597522fd7e52fe99f2a54a834101efa@0:0:0:0:0:0:0:0} <script>: [DEBUG] Au=1063362@some.domain au=<null> aU=<null> ar=<null> fU=1063362 fu=sip:1063362@some.domain -
```

After a 401 challenge, the following log statements look like this one:

```
Sep  5 01:54:40 csbc01 csbc[20385]: NOTICE: {1 2 REGISTER f597522fd7e52fe99f2a54a834101efa@0:0:0:0:0:0:0:0} <script>: [DEBUG] Au=1063362@some.domain au=1063362 aU=1063362 ar=custom-realm fU=1063362 fu=sip:1063362@some.domain -
```

At this point I would expect `$Au` to not have the `@domain` part in it.

And strangely, after an `auth_check()`, it changes again:

```
Sep  5 01:54:40 csbc01 csbc[20385]: NOTICE: {1 2 REGISTER f597522fd7e52fe99f2a54a834101efa@0:0:0:0:0:0:0:0} <script>: [DEBUG] Au=1063362@custom-realm au=1063362 aU=1063362 ar=custom-realm fU=1063362 fu=sip:1063362@some.domain -
```

From that point onward, it no longer has the domain and now contains the realm.

I believe both these behaviors are incorrect, or at least they don't match what the documentation says.

### Troubleshooting

@henningw commented about this in the email thread I started:

_Hello Joel,_

_I did a quick look into the code, this is basically unchanged since 2008. I also tested 5.2.3, it shows the same behavior._

_NOTICE: {1 1 REGISTER 363545605-1445114084-1880652839} <script>: [DEBUG] Au=82621@116.203.XXX.XXX au=<null> aU=<null> fU=82621 fu=sip:82621@116.203.XXX.XXX -
root@sip:~# kamcmd core.version
kamailio 5.2.3 (x86_64/linux)  
I certainly would make more sense in a way like it is documented. Can you easily check an older version?_

_Cheers,_

_Henning_

### Reproduction

Print `$Au` in logs before challenge, after a successful auth, and after an `auth_check()` 

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
root@csbc01:/etc/kamailio# kamailio -v
version: kamailio 5.3.0-dev7 (x86_64/linux)
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 8.3.0
root@csbc01:/etc/kamailio#
```

* **Operating System**:

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by henningw** [comment] 2019-09-05 17:26
Thanks Joel for the report. I fixed it in git master. This is really strange that nobody reported it before, we have indeed a lot of pseudo-variables..

**Comment by joelsdc** [comment] 2019-09-05 17:48
Great news! I'll locally build new packages from master and test. 

I'll report back my results, thank you Henning!

**Comment by henningw** [comment] 2019-09-05 18:24
Great, let me know the results, I will then back-port the fix.

**Comment by lazedo** [comment] 2019-09-05 18:26
@henningw please hold on the `backport` as this is a changing on existing behaviour. users are currently getting the `realm` part and this change may break their scripts.

**Comment by miconda** [comment] 2019-09-05 18:27
I am not using that variable, so I don't have anything explicitly again, but the code being that old might have been how it was intended to work. If I am not wrong, @juha-h added some of the $aX or $AX variables related to auth header/acc, so maybe he can comment if he is using or not.

**Comment by henningw** [comment] 2019-09-05 18:38
@lazedo - good point, in the end nobody complained about it in a long time. So my suggestion would be to to keep the old functionality in stable branches and document the change in 5.3 migration document. I googled for this PV, did not found something on the net so far.

**Comment by miconda** [comment] 2019-09-05 19:08
Looking at the patch, it is rather clear that the developer wanted to have @ realm, because there is explicit concatenation. So I think the correct way would be to fix documentation based on code, not the code based on wiki documentation, specially given the age of the code in this case. Eventually a new variable can be added if something else is needed.

**Comment by henningw** [comment] 2019-09-05 19:30
It is rather strange, it was introduced in kamailio 1.4.0 and the wrong documentation were added to the old wiki.. I will revert the patch. 
@joelsdc - I will introduce a new PV "$AU" with the documented behavior.
@miconda - ok to add it now or after un-freezing git master again?

**Comment by joelsdc** [comment] 2019-09-05 19:33
Sounds good! I hope it can make it to 5.3 :)

**Comment by miconda** [comment] 2019-09-05 19:58
@joelsdc: regarding the description of the issue - Kamailio doesn't return values for auth-header related variable before authentication is done, they are not set before auth_check()/proxy_authenticate()/... That's because a SIP request can have many Proxy-/Authorize headers with different realm and kamailio has to know which one is corresponding for itself along. Moreover, after authentication is validated, you are sure it a valid username that used a valid password.

@henningw: personally I am not opposing to add it at this stage, if other developers have nothing against. If other developers don't feel comfortable with it, then a solution that can be used now in config is $(Au{s.select,0,@})

**Comment by joelsdc** [comment] 2019-09-05 21:17
@miconda: RE description: I set it while thinking on the discrepancy between docs and code but typed the behavior instead haha my bad, I updated it to be more specific, you are correct that it didn't really match the real issue. 

Using `$(Au{s.select,0,@})` works for me, I probably should have thought of it myself, thanks for the suggestion 👍

**Comment by henningw** [comment] 2019-09-06 07:32
Added, local test result ok:
Sep  6 09:19:06 sip /usr/local/kamailio-devel/sbin/kamailio[21683]: ERROR: {1 16560 REGISTER hRVTMJWimNjq0WVwJIed6P2uIr7WTK.V} <script>: AU=123456 Au=123456@XXX.de au=123456 aU=123456 ar=XXX.de adu=sip:XXX.de fU=123456 fu=sip:123456@XXX.de fU=123456

Documentation added as well:
https://www.kamailio.org/wiki/cookbooks/devel/pseudovariables#au_-_acc_username

Close this one. @joelsdc please test as well and re-open if you see issues.

**Closed by henningw** 2019-09-06 07:32 UTC
Labels: bug
