### ISSUE TITLE
siptrace: add haproxy protocol support

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#3665] opened 2023-12-07 13:32 UTC
When used `tcp_accept_haproxy=yes` and inbound connection from load-balancer received via IPv6 protocol and client real IPv4 then i can see error in the kamailio log
```
28(723055) ERROR: {1 27 REGISTER 4fkReTbLC-} siptrace [siptrace_hep.c:94]: trace_send_hep3_duplicate(): interworking detected ?
```

Looks like requried add haproxy protocol support into siptrace module

**Comment by miconda** [comment] 2023-12-08 16:45
The problem is that source address family is different than target address family, and HEP seems to have only one field for address family:

  - https://github.com/kamailio/kamailio/blob/master/src/modules/siptrace/siptrace_hep.c#L93-L96
  - https://github.com/kamailio/kamailio/blob/master/src/modules/siptrace/siptrace_hep.c#L139

So apparently you need to extend HEP and Homer Sipcature server, not only siptrace.

I am closing it as it looks not something easily to deal with, it is not only about Kamailio. If I am wrong, you can reopen, or just make a pull request with the changes.

**Closed by miconda** 2023-12-08 16:45 UTC
