### ISSUE TITLE
Malformed INVITE message crashes Kamailio 

### ISSUE THREAD

**Issue by santoshsridhar** [kamailio/kamailio#2044] opened 2019-08-26 06:41 UTC
### Description
I have sent malformed data to kamailio server and its getting crashed.

#### Reproduction
This can be easily reproducable by remove .(eol) from each line of invite packet

#### Log Messages

```
32(78) CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 13
 0(46) ALERT: <core> [main.c:745]: handle_sigs(): child process 47 exited by a signal 11
 0(46) ALERT: <core> [main.c:748]: handle_sigs(): core was generated
 0(46) INFO: <core> [main.c:771]: handle_sigs(): terminating due to SIGCHLD
 2(48) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 6(52) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 8(54) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
12(58) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
13(59) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
15(61) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
17(63) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
18(64) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
20(66) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
22(68) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
24(70) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
26(72) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
28(74) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
32(78) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
25(71) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
21(67) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
23(69) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
14(60) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 3(49) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
29(75) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
19(65) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
30(76) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
11(57) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 7(53) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
31(77) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
16(62) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 9(55) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
27(73) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
10(56) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 4(50) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 5(51) INFO: <core> [main.c:826]: sig_usr(): signal 15 received
 0(46) INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
2019/08/26 06:14:51.186871 [ERR] (cli) child process died with exit code 1
```

#### SIP Traffic

```
INVITE sip:9631793333@10.130.72.178:5060 SIP/2.0
Max-Forwards: 66
From: "9631791999" <sip:9631793333@test.santhos.com>;tag=8BpeDNKX9g7ZN
To: <sip:12254431343@52.77.251.154>
Call-ID: 0e61d723-400b-1238-5ea2-029e611e72cc
CSeq: 8715558 INVITE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 248
Remote-Party-ID: "9631793333" <sip:9631791999@test.santhos.com>;party=calling;screen=yes;privacy=off
Contact: <sip:btpsh-5d5dab4f-36-1@3.82.91.199;alias=10.130.74.48~5060~1>
User-Agent: NewServer
Accept: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,UPDATE

v=0
o=- 1566538700029766 7092256907260767331 IN IP4 xx.xx.xx.xx
s=X-Lite release 5.6.1 stamp 99140
c=IN IP4 xx.xx.xx.xx
t=0 0
m=audio 10030 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
root@test-server:/# kamailio -v
version: kamailio 5.1.4 (x86_64/linux) cc647d
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: cc647d 
compiled on 10:09:16 Jul 29 2019 with gcc 5.4.0
```

* **Operating System**:

```
root@test-server:/# cat /etc/debian_version 
stretch/sid

root@test-server:/# uname -a 
Linux test-server 4.14.77-69.57.amzn1.x86_64 #1 SMP Tue Nov 6 21:32:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment] 2019-08-26 06:48
I see that the core was generated. Can you send the full backtrace from gdb (`bt full` output)?

**Comment by santoshsridhar** [comment] 2019-08-26 06:50
k sure will get it.

**Comment by henningw** [comment] 2019-09-01 17:18
Did you managed to get the backtrace?

**Comment by santoshsridhar** [comment] 2019-09-04 09:00
I am running Kamailio as Docker container.. so core file is not available on the setup where the issue  is seen.. I am planning to have kamailio on standalone instance and will share the core file as soon as I have it.

**Comment by miconda** [comment] 2019-10-10 11:55
Any update on this one?

**Comment by miconda** [comment] 2019-10-28 08:27
Please reopen if you get further troubleshooting data.

Closing as I could not reproduce with packets without eol and is more than 1 month and a half since the reporter gave updates.

**Closed by miconda** 2019-10-28 08:27 UTC
Labels: bug
